package com.projek.sipatik.config;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.UUID;

import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

class SchemaMigrationRunnerTest {

    @Test
    void backfillStatusMenghapusKolomLamaDanTetapIdempoten() {
        JdbcTemplate jdbc = jdbcBaru();
        jdbc.execute("""
                CREATE TABLE setor_infak (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    dikonfirmasi BOOLEAN NOT NULL,
                    status VARCHAR(20)
                )
                """);
        jdbc.update("INSERT INTO setor_infak (dikonfirmasi, status) VALUES (?, ?)", true, null);
        jdbc.update("INSERT INTO setor_infak (dikonfirmasi, status) VALUES (?, ?)", false, null);
        jdbc.update("INSERT INTO setor_infak (dikonfirmasi, status) VALUES (?, ?)", false, "DITOLAK");

        SchemaMigrationRunner runner = new SchemaMigrationRunner(jdbc);
        assertDoesNotThrow(() -> runner.run());

        List<String> status = jdbc.queryForList("SELECT status FROM setor_infak ORDER BY id", String.class);
        assertEquals(List.of("DIKONFIRMASI", "MENUNGGU", "DITOLAK"), status);
        assertEquals(0, jumlahKolom(jdbc, "dikonfirmasi"));

        // Entity baru tidak lagi mengirim dikonfirmasi. Insert semacam ini dulu gagal
        // ketika kolom boolean lama masih memiliki constraint NOT NULL.
        assertEquals(1, jdbc.update("INSERT INTO setor_infak (status) VALUES (?)", "MENUNGGU"));
        assertDoesNotThrow(() -> runner.run());
    }

    @Test
    void menggagalkanStartupJikaKolomStatusBelumTerbentuk() {
        JdbcTemplate jdbc = jdbcBaru();
        jdbc.execute("""
                CREATE TABLE setor_infak (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    dikonfirmasi BOOLEAN NOT NULL
                )
                """);

        IllegalStateException error = assertThrows(
                IllegalStateException.class,
                () -> new SchemaMigrationRunner(jdbc).run());

        assertEquals("Migrasi skema kritis gagal", error.getMessage());
        assertTrue(error.getCause().getMessage().contains("Kolom status belum terbentuk"));
        assertEquals(1, jumlahKolom(jdbc, "dikonfirmasi"));
    }

    @Test
    void menormalisasiEmailDanMenambahkanConstraintUnikSecaraIdempoten() {
        JdbcTemplate jdbc = jdbcBaru();
        jdbc.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, email VARCHAR(255))");
        jdbc.update("INSERT INTO users (id, email) VALUES (?, ?)", 1L, " Alumni@Example.ORG ");
        jdbc.update("INSERT INTO users (id, email) VALUES (?, ?)", 2L, "   ");
        jdbc.update("INSERT INTO users (id, email) VALUES (?, ?)", 3L, null);

        SchemaMigrationRunner runner = new SchemaMigrationRunner(jdbc);
        assertDoesNotThrow(() -> runner.run());
        assertDoesNotThrow(() -> runner.run());

        assertEquals("alumni@example.org",
                jdbc.queryForObject("SELECT email FROM users WHERE id = 1", String.class));
        assertNull(jdbc.queryForObject("SELECT email FROM users WHERE id = 2", String.class));
        assertThrows(Exception.class,
                () -> jdbc.update("INSERT INTO users (id, email) VALUES (?, ?)", 4L, "alumni@example.org"));
    }

    @Test
    void menggagalkanStartupBilaEmailBentrokSetelahNormalisasi() {
        JdbcTemplate jdbc = jdbcBaru();
        jdbc.execute("CREATE TABLE users (id BIGINT PRIMARY KEY, email VARCHAR(255))");
        jdbc.update("INSERT INTO users (id, email) VALUES (?, ?)", 1L, "same@example.org");
        jdbc.update("INSERT INTO users (id, email) VALUES (?, ?)", 2L, " SAME@example.org ");

        IllegalStateException error = assertThrows(
                IllegalStateException.class,
                () -> new SchemaMigrationRunner(jdbc).run());

        assertEquals("Migrasi skema kritis gagal", error.getMessage());
        assertTrue(error.getCause().getMessage().contains("email user duplikat"));
    }

    private JdbcTemplate jdbcBaru() {
        String namaDb = "migration_" + UUID.randomUUID().toString().replace("-", "");
        DriverManagerDataSource dataSource = new DriverManagerDataSource(
                "jdbc:h2:mem:" + namaDb + ";MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DATABASE_TO_LOWER=TRUE",
                "sa",
                "");
        return new JdbcTemplate(dataSource);
    }

    private int jumlahKolom(JdbcTemplate jdbc, String namaKolom) {
        Integer jumlah = jdbc.queryForObject(
                "SELECT COUNT(*) FROM information_schema.columns "
                        + "WHERE LOWER(table_name) = 'setor_infak' AND LOWER(column_name) = ?",
                Integer.class,
                namaKolom);
        return jumlah == null ? 0 : jumlah;
    }
}
